### ISSUE TITLE
Add Russia

### ISSUE THREAD

**Issue by mentaljam** [black-sheep-dev/harbour-mlsmanager#1]
Hi,

Thanks for your work! And I'm glad my experience helped you. I also can offer you to add Russian Federation to supported countries. You can pull my [commit](https://github.com/mentaljam/geoclue-providers-mlsdb/commit/8c9cc816225505f0834c7f1a2773bfef00799149) if you wish.

P.S. I wrote to you via the OpenRepos form, but I think the message may have ended up in spam.

**Comment by black-sheep-dev** [comment]
Hi,

thank you for your commit. I have added it to my instance. RU Package is uploading at the moment.
