### ISSUE TITLE
Allow installing multiple countries at once

### ISSUE THREAD

**Issue by ddobrev** [black-sheep-dev/harbour-mlsmanager#13]
At present each country must be installed individually. There's no option to either multi-select or install entire regions. The need to press and hold instead of just tap to install further slows the process down.

**Comment by black-sheep-dev** [comment]
The idea was to minimize space on the device by installing only needed countries. The installation of each country is an one time job. So would it be a real benefit? The updates later  can be done for all installed packages at once.
I also think about to use regions, but now this could interfere with the Jolla offical packages, or I would need to choose an other naming convention.

**Comment by ddobrev** [comment]
I meant extend rather than replace. That is, add an option to install regions. This way users who prefer separate countries won't feel a difference.
