### ISSUE TITLE
Relocate data to the home partition

### ISSUE THREAD

**Issue by abranson** [black-sheep-dev/harbour-mlsmanager#2]
This MLS data is quite large, and putting it on the fairly small root partition (on official devices) might cause upgrade problems. It would be better to move the data into /home somewhere, and symlink it. There's already a /home/.system/usr directory there, where the debug symbols can be relocated to.

**Comment by black-sheep-dev** [comment]
Thanks, you are right! Packages starting with version number 2021.02.10,  files are put to "/home/.system/usr/shar/geoclue-provider-mlsdb/[$COUNTRY_CODE]" with ta symlink to "/usr/share/geoclue-provider-mlsdb/[$COUNTRY_CODE]"
