### ISSUE TITLE
Update through Chum fails due to missing -cz package

### ISSUE THREAD

**Issue by JacekJagosz** [black-sheep-dev/harbour-mlsmanager#20]
On my Xperia 10 III (aarch64) I am unable to update the app in Chum because I am getting an error that it cannot find the harbour-mls-offline-cz-2022.09.17-1.noarch.rpm.
I have been using this app previously and insfalled multiple countries including Czech Republic.
Any idea how can I fix it?

**Comment by JacekJagosz** [comment]
Wait, it just worked? I have been getting this error for last week, and now it simply updated, just after posting this bug report?! Happy it worked though!
Do you have any reliable workaround for this in the future? I remember I got this bug a few months ago as well

**Comment by black-sheep-dev** [comment]
I had the same issue some time ago. A "pkcon refresh" fixed it for me.
